import React, { createContext, useContext, useState } from "react";

export type LanguageCode = 
  | "en" | "hi" | "mr" | "gu" | "ta" | "kn" | "te" | "pa" | "bn" | "ml" | "or" | "ur";

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const languages: Language[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
  { code: "ur", name: "Urdu", nativeName: "اردو" }
];

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    title: "SMART BHARAT",
    subtitle: "AI Powered Civic Companion",
    heroTitle: "Empowering Every Indian Citizen with AI",
    heroDesc: "Your intelligent bridge to government schemes, documents, civic complaints, and nearby public services.",
    btnStartChat: "Start AI Chat",
    btnExploreSchemes: "Explore Schemes",
    btnReportIssue: "Report Civic Issue",
    btnLearnMore: "Learn More",
    navDashboard: "Dashboard",
    navAIAssistant: "AI Companion",
    navSchemes: "Scheme Portal",
    navDocuments: "Document Assistant",
    navExplainer: "Doc Explainer",
    navComplaints: "Complaint Desk",
    navTracker: "Track Complaint",
    navServices: "Nearby Services",
    navEmergency: "Emergency Mode",
    navSettings: "Settings",
    greetingMorning: "Good Morning",
    greetingAfternoon: "Good Afternoon",
    greetingEvening: "Good Evening",
    welcomeUser: "Welcome, Rahul!",
    searchPlaceholder: "Search services, schemes, documents... (Cmd+K)",
    quickActions: "Quick Actions",
    upcomingAppointments: "Upcoming Appointments",
    recentNotifications: "Notifications",
    aiRecommendations: "AI Suggestions for You",
    complaintsSolved: "Civic Complaints Resolved",
    citizensHelped: "Indian Citizens Empowered",
    schemesActive: "Active Government Schemes",
    languagesSupported: "Regional Languages Supported",

    // Added forms & interfaces translations
    labelAge: "Your Age",
    labelGender: "Gender Identity",
    labelIncome: "Annual Income (₹)",
    labelCategory: "Social Category",
    labelState: "Residential State",
    labelOccupation: "Occupation",
    btnContinue: "Continue",
    btnBack: "Back",
    btnSubmit: "Submit Form",
    btnApply: "Apply Now",
    btnAutofill: "Trigger Form Auto-Fill",
    labelFullName: "Applicant's Full Name",
    labelDocId: "Identity No (Aadhaar/PAN)",
    labelDOB: "Date of Birth",
    labelAddress: "Permanent Residential Address",
    headDemographics: "Demographic Profile",
    headRequiredDocs: "Required Documents",
    headGrievance: "Lodge Civic Grievance",
    headAudit: "Document Audit Sandbox",
    headForm: "Government Portal Application Form"
  },
  hi: {
    title: "स्मार्ट भारत",
    subtitle: "एआई संचालित नागरिक साथी",
    heroTitle: "एआई के साथ हर भारतीय नागरिक को सशक्त बनाना",
    heroDesc: "सरकारी योजनाओं, दस्तावेजों, नागरिक शिकायतों और आस-पास की सार्वजनिक सेवाओं के लिए आपका बुद्धिमान पुल।",
    btnStartChat: "चैट शुरू करें",
    btnExploreSchemes: "योजनाएं खोजें",
    btnReportIssue: "शिकायत दर्ज करें",
    btnLearnMore: "और जानें",
    navDashboard: "डैशबोर्ड",
    navAIAssistant: "एआई साथी",
    navSchemes: "योजना पोर्टल",
    navDocuments: "दस्तावेज़ सहायक",
    navExplainer: "दस्तावेज़ विश्लेषक",
    navComplaints: "शिकायत पटल",
    navTracker: "शिकायत ट्रैकर",
    navServices: "आस-पास की सेवाएं",
    navEmergency: "आपातकालीन मोड",
    navSettings: "सेटिंग्स",
    greetingMorning: "शुभ प्रभात",
    greetingAfternoon: "शुभ दोपहर",
    greetingEvening: "शुभ संध्या",
    welcomeUser: "स्वागत है, राहुल!",
    searchPlaceholder: "सेवाएं, योजनाएं, दस्तावेज़ खोजें... (Cmd+K)",
    quickActions: "त्वरित कार्रवाई",
    upcomingAppointments: "आगामी नियुक्तियां",
    recentNotifications: "सूचनाएं",
    aiRecommendations: "आपके लिए एआई सुझाव",
    complaintsSolved: "सुलझाई गई शिकायतें",
    citizensHelped: "सशक्त नागरिक",
    schemesActive: "सक्रिय सरकारी योजनाएं",
    languagesSupported: "समर्थित क्षेत्रीय भाषाएँ",

    // Added forms & interfaces translations
    labelAge: "आपकी उम्र",
    labelGender: "लिंग पहचान",
    labelIncome: "वार्षिक आय (₹)",
    labelCategory: "सामाजिक वर्ग",
    labelState: "निवासी राज्य",
    labelOccupation: "व्यवसाय",
    btnContinue: "आगे बढ़ें",
    btnBack: "पीछे जाएं",
    btnSubmit: "फॉर्म जमा करें",
    btnApply: "अभी आवेदन करें",
    btnAutofill: "फॉर्म ऑटो-फिल करें",
    labelFullName: "आवेदक का पूरा नाम",
    labelDocId: "पहचान संख्या (आधार/पैन)",
    labelDOB: "जन्म तिथि",
    labelAddress: "स्थायी आवासीय पता",
    headDemographics: "जनसांख्यिकीय प्रोफ़ाइल",
    headRequiredDocs: "आवश्यक दस्तावेज़",
    headGrievance: "नागरिक शिकायत दर्ज करें",
    headAudit: "दस्तावेज़ ऑडिट सैंडबॉक्स",
    headForm: "सरकारी पोर्टल आवेदन पत्र"
  },
  mr: {
    title: "स्मार्ट भारत",
    subtitle: "एआय समर्थित नागरिक साथी",
    heroTitle: "एआय सह प्रत्येक भारतीय नागरिकाला सक्षम करणे",
    heroDesc: "सरकारी योजना, कागदपत्रे, नागरी तक्रारी आणि जवळील सार्वजनिक सेवांसाठी तुमचा बुद्धिमान दुवा.",
    btnStartChat: "संभाषण सुरू करा",
    btnExploreSchemes: "योजना शोधा",
    btnReportIssue: "तक्रार नोंदवा",
    btnLearnMore: "अधिक जाणून घ्या",
    navDashboard: "डॅशबोर्ड",
    navAIAssistant: "एआय सहकारी",
    navSchemes: "योजना पोर्टल",
    navDocuments: "दस्तऐवज सहाय्यक",
    navExplainer: "दस्तऐवज स्पष्टीकरण",
    navComplaints: "तक्रार कक्ष",
    navTracker: "तक्रार ट्रॅकर",
    navServices: "जवळपासच्या सेवा",
    navEmergency: "आणीबाणी मोड",
    navSettings: "सेटिंग्ज",
    greetingMorning: "शुभ सकाळ",
    greetingAfternoon: "शुभ दुपार",
    greetingEvening: "शुभ संध्याकाळ",
    welcomeUser: "स्वागत आहे, राहुल!",
    searchPlaceholder: "सेवा, योजना, कागदपत्रे शोधा... (Cmd+K)",
    quickActions: "त्वरित कृती",
    upcomingAppointments: "आगामी भेटी",
    recentNotifications: "सूचना",
    aiRecommendations: "तुमच्यासाठी एआय शिफारसी",
    complaintsSolved: "नागरी तक्रारींचे निवारण",
    citizensHelped: "सक्षम केलेले नागरिक",
    schemesActive: "सक्रिय सरकारी योजना",
    languagesSupported: "समर्थित प्रादेशिक भाषा",

    // Added forms & interfaces translations
    labelAge: "तुमचे वय",
    labelGender: "लिंग",
    labelIncome: "वार्षिक उत्पन्न (₹)",
    labelCategory: "सामाजिक प्रवर्ग",
    labelState: "निवासी राज्य",
    labelOccupation: "व्यवसाय",
    btnContinue: "पुढे जा",
    btnBack: "मागे",
    btnSubmit: "अर्ज सादर करा",
    btnApply: "आता अर्ज करा",
    btnAutofill: "फॉर्म ऑटो-फिल करा",
    labelFullName: "अर्जदाराचे पूर्ण नाव",
    labelDocId: "ओळख क्रमांक (आधार/पॅन)",
    labelDOB: "जन्म तारीख",
    labelAddress: "कायमचा रहिवासी पत्ता",
    headDemographics: "डेमोग्राफिक प्रोफाइल",
    headRequiredDocs: "आवश्यक कागदपत्रे",
    headGrievance: "तक्रार नोंदवा",
    headAudit: "कागदपत्र ऑडिट सँडबॉक्स",
    headForm: "शासकीय पोर्टल अर्ज"
  },
  gu: {
    title: "સ્માર્ટ ભારત",
    subtitle: "એઆઈ સંચાલિત નાગરિક સાથી",
    heroTitle: "એઆઈ સાથે દરેક ભારતીય નાગરિકને સશક્ત બનાવવું",
    heroDesc: "સરકારી યોજનાઓ, દસ્તાવેજો, નાગરિક ફરિયાદો અને નજીકની જાહેર સેવાઓ માટે તમારો બુદ્ધિશાળी સેતુ.",
    btnStartChat: "ચેટ શરૂ કરો",
    btnExploreSchemes: "યોજનાઓ શોધો",
    btnReportIssue: "ફરિયાદ નોંધાવો",
    btnLearnMore: "વધુ જાણો",
    navDashboard: "ડૅશબોર્ડ",
    navAIAssistant: "એઆઈ સાથી",
    navSchemes: "યોજના પોર્ટલ",
    navDocuments: "દસ્તાવેજ સહાયક",
    navExplainer: "દસ્તાવેજ વિશ્લેષક",
    navComplaints: "ફરિયાદ ડેસ્ક",
    navTracker: "ફરિયાદ ટ્રેકર",
    navServices: "નજીકની સેવાઓ",
    navEmergency: "કટોકટી મોડ",
    navSettings: "સેટિંગ્સ",
    greetingMorning: "સુપ્રભાત",
    greetingAfternoon: "શુભ બપોર",
    greetingEvening: "શુભ સાંજ",
    welcomeUser: "સ્વાગત છે, રાહુલ!",
    searchPlaceholder: "સેવાઓ, યોજનાઓ, દસ્તાવેજો શોધો... (Cmd+K)",
    quickActions: "ઝડપી પગલાં",
    upcomingAppointments: "આગામી મુલાકાતો",
    recentNotifications: "સૂચનાઓ",
    aiRecommendations: "તમારા માટે એઆઈ સૂચનો",
    complaintsSolved: "નાગરિક ફરિયાદો ઉકેલાઈ",
    citizensHelped: "સશક્ત નાગરિકો",
    schemesActive: "સક્રિય સરકારી યોજનાઓ",
    languagesSupported: "સમર્થિત પ્રાદેશಿಕ ભાષાઓ",

    // Added forms & interfaces translations
    labelAge: "તમારી ઉંમર",
    labelGender: "જાતિ",
    labelIncome: "વાર્ષિક આવક (₹)",
    labelCategory: "સામાજિક શ્રેણી",
    labelState: "રહેઠાણ રાજ્ય",
    labelOccupation: "વ્યવસાય",
    btnContinue: "ચાલુ રાખો",
    btnBack: "પાછા જાઓ",
    btnSubmit: "ફોર્મ સબમિટ કરો",
    btnApply: "અત્યારે અરજી કરો",
    btnAutofill: "ફોર્મ ઓટો-ફિલ કરો",
    labelFullName: "અરજદારનું પૂરું નામ",
    labelDocId: "ઓળખ નંબર (આધાર/પાન)",
    labelDOB: "જન્મ તારીખ",
    labelAddress: "કાયમી સરનામું",
    headDemographics: "ડેમોગ્રાફિક પ્રોફાઇલ",
    headRequiredDocs: "જરૂરી દસ્તાવેજો",
    headGrievance: "નાગરિક ફરિયાદ નોંધાવો",
    headAudit: "દસ્તાવેજ ઓડિટ સેન્ડબોક્સ",
    headForm: "સરકારી પોર્ટલ અરજી પત્ર"
  },
  ta: {
    title: "ஸ்மார்ட் பாரத்",
    subtitle: "செயற்கை நுண்ணறிவு குடிமக்கள் துணை",
    heroTitle: "செயற்கை நுண்ணறிவு மூலம் ஒவ்வொரு இந்திய குடிமகனையும் மேம்படுத்துதல்",
    btnStartChat: "உரையாடலைத் தொடங்கு",
    btnExploreSchemes: "திட்டங்களை ஆராய்க",
    btnReportIssue: "புகார் அளிக்கவும்",
    btnLearnMore: "மேலும் அறிய",
    navDashboard: "டாஷ்போர்டு",
    navAIAssistant: "AI துணை",
    navSchemes: "திட்ட போர்டல்",
    navDocuments: "ஆவண உதவியாளர்",
    navExplainer: "ஆவண விளக்கமளிப்பான்",
    navComplaints: "புகார் மேசை",
    navTracker: "புகார் கண்காணிப்பு",
    navServices: "அருகிலுள்ள சேவைகள்",
    navEmergency: "அவசர நிலை",
    navSettings: "அமைப்புகள்",
    greetingMorning: "காலை வணக்கம்",
    greetingAfternoon: "மதிய வணக்கம்",
    greetingEvening: "மாலை வணக்கம்",
    welcomeUser: "வரவேற்கிறோம், ராகுல்!",
    searchPlaceholder: "சேவைகள், திட்டங்கள், ஆவணங்களைத் தேடுக... (Cmd+K)",
    quickActions: "விரைவுச் செயல்பாடுகள்",
    upcomingAppointments: "arrowசந்திப்புகள்",
    recentNotifications: "அறிவிப்புகள்",
    aiRecommendations: "உங்களுக்கான AI பரிந்துரைகள்",
    complaintsSolved: "தீர்க்கப்பட்ட புகார்கள்",
    citizensHelped: "உதவி பெற்ற குடிமக்கள்",
    schemesActive: "செயலில் உள்ள அரசு திட்டங்கள்",
    languagesSupported: "ஆதரிக்கப்படும் பிராந்திய மொழிகள்",

    // Added forms & interfaces translations
    labelAge: "உங்கள் வயது",
    labelGender: "பாலினம்",
    labelIncome: "ஆண்டு வருமானம் (₹)",
    labelCategory: "சமூகப் பிரிவு",
    labelState: "வசிக்கும் மாநிலம்",
    labelOccupation: "தொழில்",
    btnContinue: "தொடரவும்",
    btnBack: "பின்செல்ல",
    btnSubmit: "படிவத்தை சமர்ப்பிக்கவும்",
    btnApply: "இப்போது விண்ணப்பிக்கவும்",
    btnAutofill: "படிவத்தை தானாக நிரப்பவும்",
    labelFullName: "விண்ணப்பதாரரின் முழு பெயர்",
    labelDocId: "அடையாள எண் (ஆதார்/பான்)",
    labelDOB: "பிறந்த தேதி",
    labelAddress: "நிரந்தர முகவரி",
    headDemographics: "மக்கள்தொகை விவரக்குறிப்பு",
    headRequiredDocs: "தேவையான ஆவணங்கள்",
    headGrievance: "குடிமைப் புகார் அளிக்கவும்",
    headAudit: "ஆவண தணிக்கை சாண்ட்பாக்ஸ்",
    headForm: "அரசு போர்டல் விண்ணப்ப படிவம்"
  },
  kn: {
    title: "ಸ್ಮಾರ್ಟ್ ಭಾರತ್",
    subtitle: "ಎಐ ಚಾಲಿತ ನಾಗರಿಕ ಸಂಗಾತಿ",
    heroTitle: "ಎಐ ಮೂಲಕ ಪ್ರತಿಯೊಬ್ಬ ಭಾರತೀಯ ನಾಗರಿಕರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು",
    btnStartChat: "ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ",
    btnExploreSchemes: "ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    btnReportIssue: "ದೂರು ಸಲ್ಲಿಸಿ",
    btnLearnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navAIAssistant: "ಎಐ ಸಹಾಯಕಿ",
    navSchemes: "ಯೋಜನಾ ಪೋರ್ಟಲ್",
    navDocuments: "ದಾಖಲೆ ಸಹಾಯಕ",
    navExplainer: "ದಾಖಲೆ ವಿಶ್ಲೇಷಕ",
    navComplaints: "ದೂರು ವಿಭಾಗ",
    navTracker: "ದೂರು ಟ್ರ್ಯಾಕರ್",
    navServices: "ಹತ್ತಿರದ ಸೇವೆಗಳು",
    navEmergency: "ತುರ್ತು ಪರಿಸ್ถಿತಿ",
    navSettings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
    greetingMorning: "ಶುਭೋದಯ",
    greetingAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    greetingEvening: "ಶುಭ ಸಂಜೆ",
    welcomeUser: "ಸ್ವಾಗತ, ರಾಹುಲ್!",
    searchPlaceholder: "ಸೇವೆಗಳು, ಯೋಜನೆಗಳು, ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಿ... (Cmd+K)",
    quickActions: "ತ್ವರಿತ ಕ್ರಮಗಳು",
    upcomingAppointments: "ಮುಂಬರುವ ನೇಮಕಾತಿಗಳು",
    recentNotifications: "ಅಧಿಸೂಚನೆಗಳು",
    aiRecommendations: "ನಿಮಗಾಗಿ ಎಐ ಶಿಫಾರಸುಗಳು",
    complaintsSolved: "ಪರಿಹರಿಸಲಾದ ನಾಗರಿಕ ದೂರುಗಳು",
    citizensHelped: "ಸಬಲೀಕರಣಗೊಂಡ ನಾಗರಿಕರು",
    schemesActive: "ಸಕ್ರಿಯ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    languagesSupported: "ಬೆಂಬಲಿತ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳು",

    // Added forms & interfaces translations
    labelAge: "ನಿಮ್ಮ ವಯಸ್ಸು",
    labelGender: "ಲಿಂಗ",
    labelIncome: "ವಾರ್ಷಿಕ ಆದಾಯ (₹)",
    labelCategory: "ಸಾಮಾಜಿಕ ವರ್ಗ",
    labelState: "ವಾಸಿಸುವ ರಾಜ್ಯ",
    labelOccupation: "ಉದ್ಯೋಗ",
    btnContinue: "ಮುಂದುವರಿಯಿರಿ",
    btnBack: "ಹಿಂದಕ್ಕೆ",
    btnSubmit: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    btnApply: "ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    btnAutofill: "ಫಾರ್ಮ್ ಸ್ವಯಂ ಭರ್ತಿ ಮಾಡಿ",
    labelFullName: "ಅರ್ಜಿದಾರರ ಪೂರ್ಣ ಹೆಸರು",
    labelDocId: "ಗುರುತಿನ ಸಂಖ್ಯೆ (ಆಧಾರ್/ಪ್ಯಾನ್)",
    labelDOB: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    labelAddress: "ಖಾಯಂ ವಿಳಾಸ",
    headDemographics: "ಜನಸಂಖ್ಯಾ ಪ್ರೊಫೈಲ್",
    headRequiredDocs: "ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳು",
    headGrievance: "ದೂರು ದಾಖಲಿಸಿ",
    headAudit: "ದಾಖಲೆ ಆಡಿಟ್ ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್",
    headForm: "ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್ ಅರ್ಜಿ ನಮೂನೆ"
  },
  te: {
    title: "స్మార్ట్ భారత్",
    subtitle: "AI ఆధారిత సివిక్ కంపానియన్",
    heroTitle: "AI సహాయంతో ప్రతి భారతీయ పౌరుడిని శక్తివంతం చేయడం",
    btnStartChat: "చాట్ ప్రారంభించండి",
    btnExploreSchemes: "పథకాలను అన్వేషించండి",
    btnReportIssue: "ఫిర్యాదు చేయండి",
    btnLearnMore: "మరింత తెలుసుకోండి",
    navDashboard: "డాష్‌బోర్డ్",
    navAIAssistant: "AI సహాయకుడు",
    navSchemes: "పథకాల పోర్టల్",
    navDocuments: "డాక్యుమెంట్ అసిస్టెంట్",
    navExplainer: "డాక్యుమెంట్ విశ్లేషణ",
    navComplaints: "ఫిర్యాదుల డెస్క్",
    navTracker: "ఫిర్యాదు ట్రాకర్",
    navServices: "సమీప సేవలు",
    navEmergency: "అత్యవసర మోడ్",
    navSettings: "సెట్టింగులు",
    greetingMorning: "శుభోదయం",
    greetingAfternoon: "శుభ మధ్యాహ్నం",
    greetingEvening: "శుభ సాయంత్రం",
    welcomeUser: "స్వాగతం, రాహుల్!",
    searchPlaceholder: "సేవలు, పథకాలు, డాక్యుమెంట్లు వెతకండి... (Cmd+K)",
    quickActions: "త్వరిత చర్యలు",
    upcomingAppointments: "రాబోయే నియామకాలు",
    recentNotifications: "నోటిఫికేషన్లు",
    aiRecommendations: "మీ కోసం AI సిఫార్సులు",
    complaintsSolved: "పరిష్కరించబడిన పౌర ఫిర్యాదులు",
    citizensHelped: "సహాయం పొందిన పౌరులు",
    schemesActive: "క్రియాశీల ప్రభుత్వ పథకాలు",
    languagesSupported: "మద్దతు ఉన్న ప్రాంతీయ భాషలు",

    // Added forms & interfaces translations
    labelAge: "మీ వయస్సు",
    labelGender: "లింగం",
    labelIncome: "సంవత్సర ఆదాయం (₹)",
    labelCategory: "సామాజిక వర్గం",
    labelState: "నివాస రాష్ట్రం",
    labelOccupation: "ఉద్యోగం",
    btnContinue: "కొనసాగించండి",
    btnBack: "వెనుకకు",
    btnSubmit: "ఫారమ్ సమర్పించండి",
    btnApply: "ఇప్పుడే దరఖాస్తు చేసుకోండి",
    btnAutofill: "ఫారమ్ ఆటో-ఫిల్ చేయండి",
    labelFullName: "దరఖాస్తుదారు పూర్తి పేరు",
    labelDocId: "గుర్తింపు సంఖ్య (ఆధార్/పాన్)",
    labelDOB: "పుట్టిన తేదీ",
    labelAddress: "శాశ్వత చిరునామా",
    headDemographics: "జనాభా ప్రొఫైల్",
    headRequiredDocs: "అవసరమైన పత్రాలు",
    headGrievance: "పౌర ఫిర్యాదు చేయండి",
    headAudit: "డాక్యుమెంట్ ఆడిట్ శాండ్‌బాక్స్",
    headForm: "ప్రభుత్వ పోర్టల్ దరఖాస్తు ఫారమ్"
  },
  pa: {
    title: "ਸਮਾਰਟ ਭਾਰਤ",
    subtitle: "AI ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਨਾਗਰਿਕ ਸਾਥੀ",
    heroTitle: "AI ਨਾਲ ਹਰ ਭਾਰਤੀ ਨਾਗਰਿਕ ਨੂੰ ਸਸ਼ਕਤ ਬਣਾਉਣਾ",
    btnStartChat: "ਚੈਟ ਸ਼ੁਰੂ ਕਰੋ",
    btnExploreSchemes: "ਯੋਜਨਾਵਾਂ ਦੇਖੋ",
    btnReportIssue: "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
    btnLearnMore: "ਹੋਰ ਜਾਣੋ",
    navDashboard: "ਡੈਸ਼ਬੋਰਡ",
    navAIAssistant: "AI ਸਾਥੀ",
    navSchemes: "ਯੋਜਨਾ ਪੋਰਟਲ",
    navDocuments: "ਦਸਤਾਵੇਜ਼ ਸਹਾਇਕ",
    navExplainer: "ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਕ",
    navComplaints: "ਸ਼ਿਕਾਇਤ ਡੈਸਕ",
    navTracker: "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕਰ",
    navServices: "ਨੇੜਲੀਆਂ ਸੇਵਾਵਾਂ",
    navEmergency: "ਐਮਰਜੈਂਸੀ ਮੋਡ",
    navSettings: "ਸੈਟਿੰਗਾਂ",
    greetingMorning: "ਸ਼ੁਭ ਸਵੇਰ",
    greetingAfternoon: "ਦੁਪਹਿਰ ਦੀ ਸੁਭਕਾਮਨਾ",
    greetingEvening: "ਸ਼ੁਭ ਸ਼ਾਮ",
    welcomeUser: "ਜੀ ਆਇਆਂ ਨੂੰ, ਰਾਹੁਲ!",
    searchPlaceholder: "ਸੇਵਾਵਾਂ, ਯੋਜਨਾਵਾਂ, ਦਸਤਾਵੇਜ਼ ਲੱਭੋ... (Cmd+K)",
    quickActions: "ਤੁਰੰਤ ਕਾਰਵਾਈ",
    upcomingAppointments: "ਆਉਣ ਵਾਲੀਆਂ ਨਿਯੁਕਤੀਆਂ",
    recentNotifications: "ਨੋਟੀਫਿਕੇਸ਼ਨ",
    aiRecommendations: "ਤੁਹਾਡੇ ਲਈ AI ਸੁਝਾਅ",
    complaintsSolved: "ਹੱਲ ਕੀਤੀਆਂ ਨਾਗਰਿਕ ਸ਼ਿਕਾਇਤਾਂ",
    citizensHelped: "ਸਸ਼ਕਤ ਨਾਗਰਿਕ",
    schemesActive: "ਸਰਗਰਮ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
    languagesSupported: "ਸਮਰਥਿਤ ਖੇਤਰੀ ਭਾਸ਼ਾਵਾਂ",

    // Added forms & interfaces translations
    labelAge: "ਤੁਹਾਡੀ ਉਮਰ",
    labelGender: "ਲਿੰਗ",
    labelIncome: "ਸਾਲਾਨਾ ਆਮਦਨ (₹)",
    labelCategory: "ਸਮਾਜਿਕ ਸ਼੍ਰੇਣੀ",
    labelState: "ਰਿਹਾਇਸ਼ੀ ਰਾਜ",
    labelOccupation: "ਕਿੱਤਾ",
    btnContinue: "ਜਾਰੀ ਰੱਖੋ",
    btnBack: "ਪਹਿਲੇ ਪੇਜ",
    btnSubmit: "ਫਾਰਮ ਜਮ੍ਹਾਂ ਕਰੋ",
    btnApply: "ਹੁਣੇ ਅਪਲਾਈ ਕਰੋ",
    btnAutofill: "ਫਾਰਮ ਆਟੋ-ਫਿਲ ਕਰੋ",
    labelFullName: "ਬਿਨੈਕਾਰ ਦਾ ਪੂਰਾ ਨਾਮ",
    labelDocId: "ਪਛਾਣ ਨੰਬਰ (ਆਧਾਰ/ਪੈਨ)",
    labelDOB: "ਜਨਮ ਤਾਰੀਖ",
    labelAddress: "ਪੱਕਾ ਪਤਾ",
    headDemographics: "ਜਨਸੰਖਿਆ ਪ੍ਰੋਫਾਈਲ",
    headRequiredDocs: "ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼",
    headGrievance: "ਨਾਗਰਿਕ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
    headAudit: "ਦਸਤਾਵੇਜ਼ ਆਡਿਟ ਸੈਂਡਬੌਕਸ",
    headForm: "ਸਰਕਾਰੀ ਪੋਰਟਲ ਬਿਨੈ-ਪੱਤਰ"
  },
  bn: {
    title: "স্মার্ট ভারত",
    subtitle: "এআই চালিত নাগরিক সাথী",
    heroTitle: "এআই এর সাথে প্রতিটি ভারতীয় নাগরিককে ক্ষমতায়ন করা",
    btnStartChat: "চ্যাট শুরু করুন",
    btnExploreSchemes: "প্রকল্পগুলি অন্বেষণ করুন",
    btnReportIssue: "অভিযোগ জমা দিন",
    btnLearnMore: "আরও জানুন",
    navDashboard: "ড্যাশবোর্ড",
    navAIAssistant: "এআই সহযোগী",
    navSchemes: "প্রকল্প পোর্টাল",
    navDocuments: "নথিপত্র সহকারী",
    navExplainer: "নথি ব্যাখ্যাকর্তা",
    navComplaints: "অভিযোগ ডেস্ক",
    navTracker: "অভিযোগ ট্র্যাকার",
    navServices: "কাছাকাছি পরিষেবা",
    navEmergency: "জরুরী মোড",
    navSettings: "সেটিংস",
    greetingMorning: "সুপ্রভাত",
    greetingAfternoon: "শুভ অপরাহ্ন",
    greetingEvening: "শুভ সন্ধ্যা",
    welcomeUser: "স্বাগতম, রাহুল!",
    searchPlaceholder: "পরিষেবা, প্রকল্প, নথি খুঁজুন... (Cmd+K)",
    quickActions: "দ্রুত পদক্ষেপ",
    upcomingAppointments: "আসন্ন অ্যাপয়েন্টমেন্ট",
    recentNotifications: "বিজ্ঞপ্তি",
    aiRecommendations: "আপনার জন্য এআই সুপারিশ",
    complaintsSolved: "মীমাংসা করা नागरिक অভিযোগ",
    citizensHelped: "ক্ষমতায়ন করা নাগরিক",
    schemesActive: "সক্রিয় সরকারি প্রকল্প",
    languagesSupported: "সমর্থিত আঞ্চলিক ভাষা",

    // Added forms & interfaces translations
    labelAge: "আপনার বয়স",
    labelGender: "লিঙ্গ",
    labelIncome: "বার্ষিক আয় (₹)",
    labelCategory: "সামাজিক বিভাগ",
    labelState: "বসবাসের রাজ্য",
    labelOccupation: "পেশা",
    btnContinue: "চালিয়ে যান",
    btnBack: "ফিরে যান",
    btnSubmit: "ফর্ম জমা দিন",
    btnApply: "এখনই আবেদন করুন",
    btnAutofill: "ফর্ম অটো-ফিল করুন",
    labelFullName: "আবেদনকারীর পুরো নাম",
    labelDocId: "পরিচয়পত্র নম্বর (আধার/প্যান)",
    labelDOB: "জন্ম তারিখ",
    labelAddress: "স্থায়ী ঠিকানা",
    headDemographics: "জনসংখ্যা প্রোফাইল",
    headRequiredDocs: "প্রয়োজনীয় নথি",
    headGrievance: "নাগরিক অভিযোগ দায়ের করুন",
    headAudit: "নথি অডিট স্যান্ডবক্স",
    headForm: "সরকারি পোর্টাল আবেদনপত্র"
  },
  ml: {
    title: "സ്മാർട്ട് ഭാരത്",
    subtitle: "AI അധിഷ്ഠിത സിവിക് കമ്പാനിയൻ",
    heroTitle: "AI ഉപയോഗിച്ച് ഓരോ ഇന്ത്യൻ പൗരനെയും ശാക്തീകരിക്കുന്നു",
    btnStartChat: "ചാറ്റ് ആരംഭിക്കുക",
    btnExploreSchemes: "പദ്ധതികൾ കാണുക",
    btnReportIssue: "പരാതി നൽകുക",
    btnLearnMore: "കൂടുതലറിയാൻ",
    navDashboard: "ഡാഷ്‌ബോർഡ്",
    navAIAssistant: "AI സഹായി",
    navSchemes: "പദ്ധതി പോർട്ടൽ",
    navDocuments: "രേഖാ സഹായി",
    navExplainer: "രേഖാ വിശകലനം",
    navComplaints: "പരാതി പരിഹാര കേന്ദ്രം",
    navTracker: "പരാതി ട്രാക്കർ",
    navServices: "അടുത്തുള്ള സേവനങ്ങൾ",
    navEmergency: "അടിയന്തിര ഘട്ടം",
    navSettings: "ക്രമീകരണങ്ങൾ",
    greetingMorning: "സുപ്രഭാതം",
    greetingAfternoon: "ശുഭ ഉച്ചനേരം",
    greetingEvening: "ശുഭ സായാഹ്നം",
    welcomeUser: "സ്വാഗതം, രാഹുൽ!",
    searchPlaceholder: "സേവനങ്ങൾ, പദ്ധതികൾ, രേഖകൾ തിരയുക... (Cmd+K)",
    quickActions: "ദ്രുത നടപടികൾ",
    upcomingAppointments: "വരാനിരിക്കുന്ന കൂടിക്കാഴ്ചകൾ",
    recentNotifications: "അറിയിപ്പുകൾ",
    aiRecommendations: "നിങ്ങൾക്കായുള്ള AI നിർദ്ദേശങ്ങൾ",
    complaintsSolved: "പരിഹരിച്ച പൗരപരാതികൾ",
    citizensHelped: "ശാക്തീകരിക്കപ്പെട്ട പൗരന്മാർ",
    schemesActive: "സജീവ സർക്കാർ പദ്ധതികൾ",
    languagesSupported: "പിന്തുണയ്ക്കുന്ന പ്രാദേശിക ഭാഷകൾ",

    // Added forms & interfaces translations
    labelAge: "നിങ്ങളുടെ പ്രായം",
    labelGender: "ലിംഗം",
    labelIncome: "വാർഷിക വരുമാനം (₹)",
    labelCategory: "സാമൂഹിക വിഭാഗം",
    labelState: "താമസിക്കുന്ന സംസ്ഥാനം",
    labelOccupation: "തൊഴിൽ",
    btnContinue: "തുടരുക",
    btnBack: "തിരികെ",
    btnSubmit: "അപേക്ഷ സമർപ്പിക്കുക",
    btnApply: "ഇപ്പോൾ അപേക്ഷിക്കുക",
    btnAutofill: "ഫോം സ്വയം പൂരിപ്പിക്കുക",
    labelFullName: "അപേക്ഷകന്റെ പൂർണ്ണനാമം",
    labelDocId: "തിരിച്ചറിയൽ നമ്പർ (ആധാർ/പാൻ)",
    labelDOB: "ജനനത്തീയതി",
    labelAddress: "സ്ഥിരമേൽവിലാസം",
    headDemographics: "ജനസംഖ്യാപരമായ പ്രൊഫൈൽ",
    headRequiredDocs: "ആവശ്യമായ രേഖകൾ",
    headGrievance: "പരാതി ഫയൽ ചെയ്യുക",
    headAudit: "രേഖാ പരിശോധന സാൻഡ്ബോക്സ്",
    headForm: "സർക്കാർ പോർട്ടൽ അപേക്ഷാ ഫോം"
  },
  or: {
    title: "ସ୍ମାର୍ଟ ଭାରତ",
    subtitle: "AI ଚାଳିତ ନାଗରିକ ସାଥୀ",
    heroTitle: "AI ସହାୟତାରେ ପ୍ରତ୍ୟେକ ଭାରତୀୟ ନାଗରିକଙ୍କୁ ସଶକ୍ତ କରିବା",
    btnStartChat: "ଚାଟ୍ ଆରମ୍ଭ କରନ୍ତୁ",
    btnExploreSchemes: "ଯୋଜନା ସନ୍ଧାନ କରନ୍ତୁ",
    btnReportIssue: "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
    btnLearnMore: "ଅଧିକ ଜାଣନ୍ତୁ",
    navDashboard: "ଡ୍ୟାସବୋର୍ଡ",
    navAIAssistant: "AI ସାଥୀ",
    navSchemes: "ଯୋଜନା ପୋର୍ଟାଲ",
    navDocuments: "ଦଲିଲ ସହାୟକ",
    navExplainer: "ଦଲିଲ ବିଶ୍ଳେଷକ",
    navComplaints: "ଅଭିଯୋਗ ଡେସ୍କ",
    navTracker: "ଅଭିଯୋଗ ଟ୍ରାକର",
    navServices: "ନିକଟସ୍ଥ ସେବା",
    navEmergency: "ଜରୁରୀକାଳୀନ ମୋଡ୍",
    navSettings: "ସେଟିଂସ",
    greetingMorning: "ଶୁଭ ସକାଳ",
    greetingAfternoon: "ଶୁଭ ଅପରାହ୍ନ",
    greetingEvening: "ଶୁଭ ସନ୍ଧ୍ୟା",
    welcomeUser: "ସ୍ୱାଗତ, ରାହୁଲ୍!",
    searchPlaceholder: "ସେବା, ଯୋଜନା, ଦଲିଲ୍ ଖୋଜନ୍ତୁ... (Cmd+K)",
    quickActions: "ତୁରନ୍ତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    upcomingAppointments: "ଆଗାମୀ ନିଯୁକ୍ତି",
    recentNotifications: "ସୂଚନାବଳୀ",
    aiRecommendations: "ଆପଣଙ୍କ ପାଇଁ AI ସୁପାରିଶ",
    complaintsSolved: "ସମାଧାନ ହୋଇଥିବା ଅଭିଯୋଗ",
    citizensHelped: "ସଶକ୍ତ ନାଗରିକ",
    schemesActive: "ସକ୍ରିୟ ସରକାରୀ ଯୋଜନା",
    languagesSupported: "ସମର୍ଥିତ ଆଞ୍ଚଳిక ଭାଷା",

    // Added forms & interfaces translations
    labelAge: "ଆପଣଙ୍କ ବୟସ",
    labelGender: "ଲିଙ୍ग",
    labelIncome: "ବାର୍ଷିକ ଆୟ (₹)",
    labelCategory: "ସାମାଜିକ ବର୍ଗ",
    labelState: "ବାସିନ୍ଦା ରାଜ୍ୟ",
    labelOccupation: "ପେଶା",
    btnContinue: "ଆଗକୁ ବଢନ୍ତୁ",
    btnBack: "ପଛକୁ ଯାଆନ୍ତୁ",
    btnSubmit: "ଫର୍म ଦାଖଲ କରନ୍ତୁ",
    btnApply: "ଏବେ ଆବେଦನ କରନ୍ତୁ",
    btnAutofill: "ଫର୍ମ ସ୍ୱୟଂ ପୂରଣ କରନ୍ତୁ",
    labelFullName: "ଆବେଦନକାରୀଙ୍କ ପୂରା ନାମ",
    labelDocId: "ପରିଚୟ ପତ୍ର ନମ୍ବର (ଆଧାର/ପ୍ୟାନ)",
    labelDOB: "ଜନ୍ମ ତାରିଖ",
    labelAddress: "ସ୍ଥାୟୀ ଠିକଣା",
    headDemographics: "ଜନସଂଖ୍ୟା ପ୍ରୋଫାଇଲ୍",
    headRequiredDocs: "ଆବଶ୍ୟକୀୟ ଦଲିଲ୍",
    headGrievance: "ନାଗରିକ ଅଭିଯୋग ଦାଖଲ କରନ୍ତୁ",
    headAudit: "ଦଲିଲ୍ ଅଡିଟ୍ ସ୍ୟାଣ୍ଡବକ୍ସ",
    headForm: "ସରକାରୀ ପୋର୍ଟାଲ୍ ଆବେଦନ ଫର୍ମ"
  },
  ur: {
    title: "اسمارٹ بھارت",
    subtitle: "اے آئی سے چلنے والا شہری ساتھی",
    heroTitle: "اے آئی کے ذریعے ہر ہندوستانی شہری کو بااختیار بنانا",
    btnStartChat: "بات چیت شروع کریں",
    btnExploreSchemes: "اسکیمیں تلاش کریں",
    btnReportIssue: "شکایت درج کریں",
    btnLearnMore: "مزید جانیں",
    navDashboard: "ڈیش بورڈ",
    navAIAssistant: "اے آئی ساتھی",
    navSchemes: "اسکیم پورٹل",
    navDocuments: "دستاویز مددگار",
    navExplainer: "دستاویز تجزیہ کار",
    navComplaints: "شکایت سیل",
    navTracker: "شکایت ٹریکر",
    navServices: "قریبی خدمات",
    navEmergency: "ہنگامی موڈ",
    navSettings: "سیٹنگز",
    greetingMorning: "صبح بخیر",
    greetingAfternoon: "دوپہر بخیر",
    greetingEvening: "شام بخیر",
    welcomeUser: "خوش آمدید، راہول!",
    searchPlaceholder: "خدمات، اسکیمیں، دستاویزات تلاش کریں... (Cmd+K)",
    quickActions: "فوری اقدامات",
    upcomingAppointments: "آنے والی ملاقاتیں",
    recentNotifications: "اطلاعات",
    aiRecommendations: "آپ کے لیے اے آئی تجاویز",
    complaintsSolved: "حل شدہ شہری شکایات",
    citizensHelped: "بااختیار شہری",
    schemesActive: "فعال سرکاری اسکیمیں",
    languagesSupported: "علاقائی زبانوں کی سپورٹ",

    // Added forms & interfaces translations
    labelAge: "آپ کی عمر",
    labelGender: "صنف",
    labelIncome: "سالانہ آمدنی (₹)",
    labelCategory: "سماجی زمرہ",
    labelState: "رہائشی ریاست",
    labelOccupation: "پیشہ",
    btnContinue: "جاری رکھیں",
    btnBack: "پیچھے",
    btnSubmit: "فارم جمع کریں",
    btnApply: "ابھی اپلائی کریں",
    btnAutofill: "فارم خودکار طریقے से بھریں",
    labelFullName: "امیدوار کا پورا نام",
    labelDocId: "شناختی نمبر (آدھار/پین)",
    labelDOB: "تاریخ پیدائش",
    labelAddress: "مستقل پتہ",
    headDemographics: "آبادیاتی معلومات",
    headRequiredDocs: "ضروری دستاویزات",
    headGrievance: "شہری شکایت درج کریں",
    headAudit: "دستاویز آڈٹ سینڈ باکس",
    headForm: "سرکاری پورٹل درخواست فارم"
  }
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  translateDynamic: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple dynamic transliteration / simulation dictionary mapping for screen texts in Hindi
const hiDynamicDict: Record<string, string> = {
  // Onboarding Slides
  "Onboarding Profile Setup": "ऑनबोर्डिंग प्रोफाइल सेटअप",
  "Step": "चरण",
  "of": "का",
  "Let's configure your profile base.": "आइए आपकी मूल प्रोफ़ाइल को कॉन्फ़िगर करें।",
  "This helps our AI system matching algorithms rank regional schemes and checks eligibility rules dynamically.": "यह हमारे एआई सिस्टम मिलान एल्गोरिदम को क्षेत्रीय योजनाओं को रैंक करने और पात्रता नियमों को गतिशील रूप से जांचने में मदद करता है।",
  "Income and region parameters.": "आय और क्षेत्र पैरामीटर।",
  "Government benefits criteria are strictly tied to family income limits and state jurisdictions.": "सरकारी लाभ मानदंड कड़ाई से पारिवारिक आय सीमा और राज्य क्षेत्राधिकार से बंधे हैं।",
  "Activity & classifications.": "गतिविधि और वर्गीकरण।",
  "Select category criteria that fit your background to unlock targeted scheme lists.": "लक्षित योजना सूचियों को अनलॉक करने के लिए अपनी पृष्ठभूमि के अनुकूल श्रेणी मानदंड चुनें।",
  "Profile config ready!": "प्रोफ़ाइल कॉन्फ़िगरेशन तैयार है!",
  "Smart Bharat AI dashboard will prioritize scholarships, public service updates, and PWD local centers coordinates matches based on this configuration.": "स्मार्ट भारत एआई डैशबोर्ड इस कॉन्फ़िगरेशन के आधार पर छात्रवृत्ति, सार्वजनिक सेवा अपडेट और पीडब्ल्यूडी स्थानीय केंद्रों के निर्देशांक मिलान को प्राथमिकता देगा।",
  "Enter Smart Bharat Platform": "स्मार्ट भारत पोर्टल में प्रवेश करें",

  // Dashboard Overview
  "Here is your personalized civic overview. Your documents are verified, and you have one upcoming appointment.": "यहाँ आपका व्यक्तिगत नागरिक विवरण है। आपके दस्तावेज़ सत्यापित हैं, और आपकी एक आगामी नियुक्ति है।",
  "Consult Civic Companion": "नागरिक साथी से परामर्श लें",
  "Grievance and Appointment Alerts": "शिकायत और नियुक्ति अलर्ट",
  "Manage Document Vault &rarr;": "दस्तावेज़ तिजोरी प्रबंधित करें →",
  "Active Documents Audit": "सक्रिय दस्तावेज़ ऑडिट",
  "Aadhaar Card Scan": "आधार कार्ड स्कैन",
  "PAN Card Scan": "पैन कार्ड स्कैन",
  "NEEDS RE-UPLOAD": "पुनः अपलोड की आवश्यकता है",
  "VERIFIED": "सत्यापित",
  "Scholarship E-KYC Verification Deadline": "छात्रवृत्ति ई-केवाईसी सत्यापन समय सीमा",
  "Road repairs assigned to ground officer": "सड़क मरम्मत कार्य क्षेत्र अधिकारी को सौंपा गया",
  "resolved": "सुलझाया गया",
  "upcoming": "आगामी",
  "critical": "महत्वपूर्ण",

  // Schemes Recommender Screen
  "AI GOVERNMENT SCHEME FINDER": "एआई सरकारी योजना खोजक",
  "Input age, income, and occupation details. The AI cross-analyzes eligibility guidelines across central databases to calculate approval odds and outline documentation gaps.": "आयु, आय और व्यवसाय विवरण दर्ज करें। एआई केंद्रीय डेटाबेस में पात्रता दिशानिर्देशों का विश्लेषण करके योजना मिलान की संभावना की गणना करता है।",
  "Demographic Profile": "जनसांख्यिकीय प्रोफ़ाइल",
  "STEP 1: DETAILS": "चरण 1: विवरण",
  "Age (Years)": "आयु (वर्ष)",
  "Gender": "लिंग",
  "Male": "पुरुष",
  "Female": "महिला",
  "Other": "अन्य",
  "Annual Income (₹)": "वार्षिक आय (₹)",
  "Social Category": "सामाजिक वर्ग",
  "General": "सामान्य",
  "OBC": "ओबीसी",
  "SC": "एससी",
  "ST": "एसटी",
  "Occupation": "व्यवसाय",
  "Profile Classifications": "प्रोफ़ाइल वर्गीकरण",
  "Student": "छात्र",
  "Farmer": "किसान",
  "Business Owner": "व्यवसाय स्वामी",
  "Disabled (UDID)": "दिव्यांग (UDID)",
  "Calculate Eligible Schemes": "पात्र योजनाओं की गणना करें",
  "Matched active schemes": "योग्य सक्रिय योजनाएं",
  "Evaluating government catalogs": "सरकारी कैटलॉग का मूल्यांकन किया जा रहा है",
  "Checking land indices, credit parameters, age caps, and tax records...": "भूमि सूचकांक, क्रेडिट पैरामीटर, आयु सीमा और कर रिकॉर्ड की जाँच की जा रही है...",
  "Scheme Description": "योजना का विवरण",
  "Entitled Benefits": "हकदार लाभ",
  "Required Documents": "आवश्यक दस्तावेज़",
  "Gaps to become eligible": "पात्र बनने के लिए कमियां",
  "Official Portal": "आधिकारिक पोर्टल",
  "Select a scheme on the left to inspect detailed specifications.": "विस्तृत विनिर्देशों की जांच करने के लिए बाईं ओर एक योजना चुनें।",
  "Audit calculations waiting": "ऑडिट गणना प्रतीक्षा में है",
  "Confirm your demographic profile details on the left, and run the calculation checklist analyzer.": "बाईं ओर अपने जनसांख्यिकीय प्रोफ़ाइल विवरण की पुष्टि करें, और पात्रता चेकर चलाएं।",
  "Central Sector Scheme of Scholarship": "केंद्रीय क्षेत्र छात्रवृत्ति योजना",
  "PM Kisan Samman Nidhi": "पीएम किसान सम्मान निधि",
  "PM Awas Yojana (PMAY-G)": "पीएम आवास योजना (ग्रामीण)",
  "Deendayal Antyodaya Yojana": "दीनदयाल अंत्योदय योजना",

  // AIChat Screen
  "Namaste! I am your AI Civic Companion. How can I assist you today? You can ask me about regional schemes, help auto-fill forms, audit document scans, or tag civic complaints. Feel free to speak or type.": "नमस्ते! मैं आपका एआई नागरिक साथी हूं। आज मैं आपकी क्या सहायता कर सकता हूं? आप मुझसे क्षेत्रीय योजनाओं के बारे में पूछ सकते हैं, फॉर्म भरने में सहायता ले सकते हैं, दस्तावेज़ स्कैन का ऑडिट कर सकते हैं, या नागरिक शिकायतों को टैग कर सकते हैं। बोलने या लिखने के लिए स्वतंत्र महसूस करें।",
  "Road outside my house is damaged.": "मेरे घर के बाहर की सड़क क्षतिग्रस्त है।",
  "Explain Aadhaar card renewal rules.": "आधार कार्ड नवीनीकरण नियम बताएं।",
  "Which schemes am I eligible for?": "मैं किन योजनाओं के लिए पात्र हूँ?",
  "How to apply for passport?": "पासपोर्ट के लिए आवेदन कैसे करें?",
  "Type or click the microphone to speak...": "बोलने के लिए लिखें या माइक्रोफ़ोन पर क्लिक करें...",
  "Vocal Off": "आवाज बंद",
  "Speaking": "बोल रहा है",
  "Attach Document (PDF)": "दस्तावेज़ संलग्न करें (PDF)",
  "Attach Photo": "फोटो संलग्न करें",
  "Listening... speak your request": "सुन रहा हूँ... अपनी बात कहें",
  "Suggested Questions": "सुझाए गए प्रश्न",
  "RAG & Translation Pipeline Active": "आरएजी और अनुवाद पाइपलाइन सक्रिय",

  // Document Assistant Screen
  "Upload Real Document Image": "वास्तविक दस्तावेज़ छवि अपलोड करें",
  "Drag/drop Aadhaar or PAN photo to scan": "स्कैन करने के लिए आधार या पैन फोटो खींचें/डालें",
  "Applicant's Full Name": "आवेदक का पूरा नाम",
  "Identity No (Aadhaar/PAN)": "पहचान संख्या (आधार/पैन)",
  "Date of Birth": "जन्म तिथि",
  "Estimated Annual Income (₹)": "अनुमानित वार्षिक आय (₹)",
  "Permanent Residential Address": "स्थायी आवासीय पता",
  "Submit Form": "फॉर्म जमा करें",
  "Trigger Form Auto-Fill": "फॉर्म ऑटो-फिल करें",
  "Audit Success: Passed Verification": "ऑडिट सफलता: सत्यापन उत्तीर्ण",
  "Document meets legal guidelines, text is readable, and layout structures match.": "दस्तावेज़ कानूनी दिशानिर्देशों को पूरा करता है, पाठ पठनीय है, और लेआउट संरचनाएं मेल खाती हैं।",
  "Parsed OCR Details (Verify & Edit)": "पार्स किए गए ओसीआर विवरण (सत्यापित करें और संपादित करें)",
  "Document ID": "दस्तावेज़ आईडी",
  "Address Details": "पते का विवरण",
  "Please select a document type above or upload an image file to trigger scanning.": "कृपया स्कैनिंग ट्रिगर करने के लिए ऊपर एक दस्तावेज़ प्रकार चुनें या एक छवि फ़ाइल अपलोड करें।",

  // Complaint Desk Screen
  "Describe the problem": "समस्या का वर्णन करें",
  "Attach photos of potholes, leakage, street light, etc.": "गड्ढों, रिसाव, स्ट्रीट लाइट आदि की तस्वीरें संलग्न करें।",
  "Submit Civic Grievance": "नागरिक शिकायत दर्ज करें",
  "Grievance Submission Log": "शिकायत जमा करने का लॉग",
  "Active Stage": "सक्रिय चरण",
  "Estimated resolution time:": "अनुमानित समाधान समय:",
  "No Complaint Active": "कोई शिकायत सक्रिय नहीं",
  "Select a grievance entry from the log history or file a new report to trigger interactive timeline progress updates.": "लॉग इतिहास से एक शिकायत प्रविष्टि चुनें या इंटरैक्टिव टाइमलाइन प्रगति अपडेट ट्रिगर करने के लिए एक नई रिपोर्ट दर्ज करें।"
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem("smart_bharat_lang");
    return (saved as LanguageCode) || "en";
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem("smart_bharat_lang", lang);
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key] || translations["en"][key] || key;
  };

  // Dynamically translates large bodies of text to selected language, simulating translation algorithms
  const translateDynamic = (text: string): string => {
    if (currentLanguage === "en") return text;
    
    // Simulate Hindi Translation mapping
    if (currentLanguage === "hi") {
      return hiDynamicDict[text] || text;
    }

    // Heuristically appends a translation indicator for other languages to simulate translation
    const names: Record<LanguageCode, string> = {
      en: "", hi: "", mr: "(मराठी)", gu: "(ગુજરાતી)", ta: "(தமிழ்)", kn: "(ಕನ್ನಡ)", 
      te: "(తెలుగు)", pa: "(ਪੰਜਾਬੀ)", bn: "(বাংলা)", ml: "(മലയാളം)", or: "(ଓଡ଼ିଆ)", ur: "(اردو)"
    };
    return `${names[currentLanguage]} ${text}`;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, translateDynamic }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
